# Generated by Django 4.2.16 on 2024-09-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
